Adding compatibility for compilation of Coq 8.0 with OCaml 3.12.1 and camlp5 6.14.
This includes various patches from 8.1 + manual updates.

* Prise en compte de la possibilité d'utiliser camlp5 (voire nécessité
d'utiliser camlp5 si en ocaml 3.10) [basé sur le patch de Pierre pour
le trunk]

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/v8.1@10185 85f007b7-540e-0410-9357-904b9bb8a0f7

Conflicts:
	CHANGES
	Makefile
	Makefile.dep
	configure
	lib/util.ml
	parsing/argextend.ml4
	parsing/egrammar.mli
	parsing/pcoq.mli
	parsing/q_coqast.ml4
	toplevel/mltop.ml4

* Support for camlp5 6.02.0 (Closes: #2432)

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/v8.1@13646 85f007b7-540e-0410-9357-904b9bb8a0f7

* Fix build with camlp5 6.02.1

Equivalent to r13687, this should fix "Print Grammar" in coqide with
camlp5 6.02.1.

This needs a fix in camlp5 6.02.1 (applied in upstream CVS):

  sed 's/None -> patt pc p/None -> pprintf pc "~%p" patt p/' etc/pr_o.ml

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/v8.1@13705 85f007b7-540e-0410-9357-904b9bb8a0f7

* - Modularisation accrue des loc pour facilisation compatibilité camlp5
- option -rectypes pour facilitation compatibilité ocaml 3.10

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/v8.1@10087 85f007b7-540e-0410-9357-904b9bb8a0f7

Conflicts:
	config/Makefile.template
	parsing/g_xml.ml4
	parsing/ppconstr.ml
	parsing/q_util.ml4
	toplevel/toplevel.ml
	translate/ppvernacnew.ml

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -22,9 +22,61 @@ for i in $PATH; do
 done
 }
 
+usage () {
+    echo -e "Available options for configure are:\n"
+    echo "-help"
+    echo -e "\tDisplays this help page\n"
+    echo "-prefix <dir>"
+    echo -e "\tSet installation directory to <dir>\n"
+    echo "-local"
+    echo -e "\tSet installation directory to the current source tree\n"
+    echo "-src"
+    echo -e "\tSpecifies the source directory\n"
+    echo "-bindir"
+    echo "-libdir"
+    echo "-mandir"
+    echo -e "\tSpecifies where to install bin/lib/man files resp.\n"
+    echo "-emacslib"
+    echo "-emacs"
+    echo -e "\tSpecifies where emacs files are to be installed\n"
+    echo "-coqdocdir"
+    echo -e "\tSpecifies where Coqdoc style files are to be installed\n"
+    echo "-camldir"
+    echo -e "\tSpecifies the path to the OCaml library\n"
+    echo "-lablgtkdir"
+    echo -e "\tSpecifies the path to the Lablgtk library\n"
+    echo "-camlp5dir"
+    echo -e "\tSpecifies where to look for the Camlp5 library and tells to use it\n"
+    echo "-arch"
+    echo -e "\tSpecifies the architecture\n"
+    echo "-opt"
+    echo -e "\tSpecifies whether or not to generate optimized executables\n"
+    echo "-fsets (all|basic)"
+    echo "-reals (all|basic)"
+    echo -e "Specifies whether or not to compile full FSets/Reals library\n"
+    echo "-coqide (opt|byte|no)"
+    echo -e "\tSpecifies whether or not to compile Coqide\n"
+    echo "-with-geoproof (yes|no)"
+    echo -e "\tSpecifies whether or not to use Geoproof binding\n"
+    echo "-with-cc <file>"
+    echo "-with-ar <file>"
+    echo "-with-ranlib <file>"
+    echo -e "\tTells configure where to find gcc/ar/ranlib executables\n"
+    echo "-byte-only"
+    echo -e "\tCompiles only bytecode version of Coq\n"
+    echo "-debug"
+    echo -e "\tAdd debugging information in the Coq executables\n"
+    echo "-profile"
+    echo -e "\tAdd profiling information in the Coq executables\n"
+    echo "-annotate"
+    echo -e "\tCompiles Coq with -dtypes option"
+}
+
+
+# Default OCaml binaries
 bytecamlc=ocamlc
 nativecamlc=ocamlopt
-camlp4o=camlp4o
+camlp4oexec=camlp4o
 coq_debug_flag=
 coq_profile_flag=
 best_compiler=opt
@@ -75,11 +127,20 @@ while : ; do
     -coqdocdir|--coqdocdir) coqdocdir_spec=yes
 	              coqdocdir="$2"
 		      shift;;
+    -camldir|--camldir) camldir_spec=yes
+	                camldir="$2"
+			shift;;
+    -lablgtkdir|--lablgtkdir) lablgtkdir_spec=yes
+	                lablgtkdir="$2"
+			shift;;
+    -camlp5dir|--camlp5dir)
+	                camlp5dir="$2"
+			shift;;
     -arch|--arch) arch_spec=yes
                   arch=$2
 		  shift;;
     -opt|--opt) bytecamlc=ocamlc.opt
-                camlp4o=camlp4o  # can't add .opt since dyn load'll be required
+                camlp4oexec=camlp4o  # can't add .opt since dyn load'll be required
                 nativecamlc=ocamlopt.opt;;
     -reals|--reals) reals_opt=yes
 		    reals=$2
@@ -124,6 +185,8 @@ case $arch_spec in
 	    # cygwin returns a name of the form /cygdrive/c/... 
 	    # that coqc does not understand; need to transform it
 	    COQTOP=`echo $COQTOP | sed -e "s#.*cygdrive.\(.\)#\1:#"`
+	elif test -x /bin/uname ; then
+	    ARCH=`/bin/uname -s`
 	elif test -x /usr/bin/uname ; then
 	    ARCH=`/usr/bin/uname -s`
 	else
@@ -185,18 +248,23 @@ CAMLBIN=`dirname "$CAMLC"`
 CAMLVERSION=`"$CAMLC" -v | sed -n -e 's|.*version* *\(.*\)$|\1|p' `
 
 case $CAMLVERSION in
-  1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05|3.08.0)
+    1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05|3.06|3.08.0)
 	echo "Your version of Objective-Caml is $CAMLVERSION."
 	if [ "$CAMLVERSION" = "3.08.0" ] ; then
-	  echo "You need Objective-Caml 3.06 or later (to the exception of 3.08.0)!"
+	    echo "You need Objective-Caml 3.07 or later (to the exception of 3.08.0)!"
 	else
-	  echo "You need Objective-Caml 3.06 or later!";
+	    echo "You need Objective-Caml 3.07 or later!"
 	fi
 	echo "Configuration script failed!"
 	exit 1;;
-  3.06|3.07*|3.08*)
+    3.07*)
+        cflags="$cflags -DOCAML_307"
+	coq_inline_flag="-inline 0"
 	echo "You have Objective-Caml $CAMLVERSION. Good!";;
-  ?*)
+    3.08*)
+	coq_inline_flag="-inline 0"
+	echo "You have Objective-Caml $CAMLVERSION. Good!";;
+    ?*)
 	CAMLP4COMPAT="-loc loc" 
 	echo "You have Objective-Caml $CAMLVERSION. Good!";;
   *)
@@ -224,12 +292,48 @@ fi
 
 # For coqmktop
 
-CAMLLIB=`"$CAMLC" -where`
+# For coqmktop & bytecode compiler
 
-# Camlp4 (greatly simplified since merged with ocaml)
+case $ARCH in
+    win32) # Awfull trick to get around a ^M problem at the end of CAMLLIB
+      CAMLLIB=`"$CAMLC" -where | sed -e 's/^\(.*\)$/\1/'` ;;
+    *)
+      CAMLLIB=`"$CAMLC" -where`
+  esac
+  
 
+# Camlp4 / Camlp5 configuration
+# Very basic for the moment: if camlp5 exists, we use it...
+
+if [ "$camlp5dir" != "" ]; then
+    CAMLP4=camlp5
+    CAMLP4LIB=$camlp5dir
+    camlp4oexec=`echo $camlp4oexec | sed -e 's/4/5/'`
+elif [ "$CAMLTAG" = "OCAML310" ]; then
+    if [ -x "${CAMLLIB}/camlp5" ]; then 
+	CAMLP4=camlp5
+    elif [ -x "${CAMLLIB}/site-lib/camlp5" ]; then 
+	CAMLP4=site-lib/camlp5
+    else
+	echo "Objective Caml 3.10 found but no Camlp5 installed"
+	echo "Configuration script failed!"
+	exit 1
+    fi
+    CAMLP4LIB=+$CAMLP4
+    camlp4oexec=`echo $camlp4oexec | sed -e 's/4/5/'`
+else 
+    CAMLP4=camlp4
+    CAMLP4LIB=+$CAMLP4
+fi
+
+case $CAMLP4LIB in
+    +*) FULLCAMLP4LIB=$COQLIB/`echo $CAMLPALIB | cut -b 2-`;;
+    *)  FULLCAMLP4LIB=$CAMLP4LIB;;
+esac
+
+# Assume that camlp(4|5) binaries are at the same place as ocaml ones
+# (this should become configurable some day) 
 CAMLP4BIN=${CAMLBIN}
-CAMLP4LIB=+camlp4
 
 # OS dependent libraries
 
@@ -249,24 +353,48 @@ esac
 
 # lablgtk2 and CoqIDE
 
-if [ "$coqide_spec" = "no" ] ; then
-if test -x "${CAMLLIB}/lablgtk2" ; then
-    if grep -q -w convert_with_fallback "${CAMLLIB}/lablgtk2/glib.mli" ; then
-	if test -f "${CAMLLIB}/threads/threads.cmxa" ; then
-            echo "LablGtk2 found, native threads: native CoqIde will be available"
-	    COQIDE=opt;
-        else
-            echo "LablGtk2 found, no native threads: bytecode CoqIde will be available"
-	    COQIDE=byte
-	fi
-    else
-        echo "LablGtk2 found but too old: CoqIde will not be available"
-        COQIDE=no;
-    fi
-else
-    echo "LablGtk2 not found: CoqIde will not be available"
-    COQIDE=no
+# -byte-only should imply -coqide byte, unless the user decides otherwise
+
+if [ "$best_compiler" = "byte" -a "$coqide_spec" = "no" ]; then 
+    coqide_spec=yes
+    COQIDE=byte
 fi
+
+# Which coqide is asked ? which one is possible ?
+
+if [ "$coqide_spec" = "yes" -a "$COQIDE" = "no" ]; then 
+    echo "CoqIde disabled as requested"
+else
+    case $lablgtkdir_spec in
+	no) 
+	    if [ -f "${CAMLLIB}/lablgtk2/glib.mli" ]; then
+		lablgtkdir=${CAMLLIB}/lablgtk2
+	    elif [ -f "${CAMLLIB}/site-lib/lablgtk2/glib.mli" ]; then
+		lablgtkdir=${CAMLLIB}/site-lib/lablgtk2
+	    else
+		echo "LablGtk2 not found: CoqIde will not be available"
+		COQIDE=no
+	    fi;;
+	yes)
+	    if [ ! -f "$lablgtkdir/glib.mli" ]; then
+		echo "Incorrect LablGtk2 library (glib.mli not found)"
+		echo "Configuration script failed!"
+		exit 1
+	    fi;;
+    esac
+    if [ -z "`grep -w convert_with_fallback "$lablgtkdir/glib.mli"`" ]; then
+	echo "LablGtk2 found but too old: CoqIde will not be available"
+	COQIDE=no;
+    elif [ "$coqide_spec" = "yes" -a "$COQIDE" = "byte" ]; then 
+	echo "LablGtk2 found, bytecode CoqIde will be used as requested"
+	COQIDE=byte
+    elif [ ! -f "${CAMLLIB}/threads/threads.cmxa" ]; then 
+	echo "LablGtk2 found, no native threads: bytecode CoqIde will be available"
+	COQIDE=byte
+    else 
+	echo "LablGtk2 found, native threads: native CoqIde will be available"
+	COQIDE=opt
+    fi
 fi
 
 if [ $COQIDE != no ] ; then
@@ -473,6 +601,7 @@ let bindir = "$ESCBINDIR"
 let coqlib = "$ESCLIBDIR"
 let coqtop = "$ESCCOQTOP"
 let camllib = "$ESCCAMLLIB"
+let camlp4 = "$CAMLP4"
 let camlp4lib = "$ESCCAMLP4LIB"
 let best = "$best_compiler"
 let arch = "$ARCH"
@@ -546,7 +675,7 @@ sed -e "s|LOCALINSTALLATION|$local|" \
     -e "s|CAMLTAG|$CAMLTAG|" \
     -e "s|CAMLP4BINDIRECTORY|$ESCCAMLP4BIN|" \
     -e "s|CAMLP4LIBDIRECTORY|$CAMLP4LIB|" \
-    -e "s|CAMLP4TOOL|$camlp4o|" \
+    -e "s|CAMLP4TOOL|$camlp4oexec|" \
     -e "s|CAMLP4COMPATFLAGS|$CAMLP4COMPAT|" \
     -e "s|COQDEBUGFLAG|$coq_debug_flag|" \
     -e "s|COQPROFILEFLAG|$coq_profile_flag|" \
@@ -565,14 +694,16 @@ chmod a-w $COQTOP/config/Makefile
 # Building the $COQTOP/dev/ocamldebug-v7 file
 ####################################################
 
+OCAMLDEBUGCOQ=$COQTOP/dev/ocamldebug-v7
+
 if test "$coq_debug_flag" = "-g" ; then
-  rm -f $COQTOP/dev/ocamldebug-v7
+  rm -f $OCAMLDEBUGCOQ
   sed -e "s|COQTOPDIRECTORY|$COQTOP|" \
       -e "s|COQLIBDIRECTORY|$LIBDIR|" \
       -e "s|CAMLBINDIRECTORY|$CAMLBIN|" \
-      -e "s|CAMLP4LIBDIRECTORY|$CAMLLIB/camlp4|" \
-      $COQTOP/dev/ocamldebug-v7.template > $COQTOP/dev/ocamldebug-v7
-  chmod a-w,a+x $COQTOP/dev/ocamldebug-v7
+      -e "s|CAMLP4LIBDIRECTORY|$FULLCAMLP4LIB|"\
+      $OCAMLDEBUGCOQ.template > $OCAMLDEBUGCOQ
+  chmod a-w,a+x $OCAMLDEBUGCOQ
 fi
 
 ##################################################
