Fix compilation with camlp5 in strict mode (Closes: #2487)
Patch from Daniel de Rauglaudre.

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/v8.1@15737 85f007b7-540e-0410-9357-904b9bb8a0f7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,21 +309,32 @@ if [ "$camlp5dir" != "" ]; then
     CAMLP4=camlp5
     CAMLP4LIB=$camlp5dir
     camlp4oexec=`echo $camlp4oexec | sed -e 's/4/5/'`
-elif [ "$CAMLTAG" = "OCAML310" ]; then
-    if [ -x "${CAMLLIB}/camlp5" ]; then 
-	CAMLP4=camlp5
-    elif [ -x "${CAMLLIB}/site-lib/camlp5" ]; then 
-	CAMLP4=site-lib/camlp5
-    else
-	echo "Objective Caml 3.10 found but no Camlp5 installed"
-	echo "Configuration script failed!"
-	exit 1
-    fi
-    CAMLP4LIB=+$CAMLP4
-    camlp4oexec=`echo $camlp4oexec | sed -e 's/4/5/'`
-else 
-    CAMLP4=camlp4
-    CAMLP4LIB=+$CAMLP4
+else
+    case $CAMLTAG in
+        OCAML31*)
+            if [ -x "${CAMLLIB}/camlp5" ]; then
+                CAMLP4LIB=+camlp5
+            elif [ -x "${CAMLLIB}/site-lib/camlp5" ]; then
+                CAMLP4LIB=+site-lib/camlp5
+            else
+	        echo "Objective Caml 3.10 found but no Camlp5 installed."
+	        echo "Configuration script failed!"
+	        exit 1
+            fi
+            CAMLP4=camlp5
+            camlp4oexec=`echo $camlp4oexec | sed -e 's/4/5/'`
+            ;;
+        *)
+            CAMLP4=camlp4
+            CAMLP4LIB=+camlp4
+            ;;
+    esac
+fi
+
+if [ "$CAMLP4" = "camlp5" ] && `$camlp4oexec -v 2>&1 | grep -q 5.00`; then
+    echo "Camlp5 version 5.00 not supported: versions 4.0x or >= 5.01 are OK."
+    echo "Configuration script failed!"
+    exit 1
 fi
 
 case $CAMLP4LIB in
