Compatibilité ocaml 3.09
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/branches/V8-0-bugfix@7501 85f007b7-540e-0410-9357-904b9bb8a0f7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -293,16 +293,25 @@ CAMLBIN=`dirname "$CAMLC"`
 CAMLVERSION=`"$CAMLC" -v | sed -n -e 's|.*version* *\(.*\)$|\1|p' `
 
 case $CAMLVERSION in
-  1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05)
+  1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05|3.08.0)
 	echo "Your version of Objective-Caml is $CAMLVERSION."
-	echo "You need Objective-Caml 3.06 or later !"
+	if [ "$CAMLVERSION" = "3.08.0" ] ; then
+	  echo "You need Objective-Caml 3.06 or later (to the exception of 3.08.0)!"
+	else
+	  echo "You need Objective-Caml 3.06 or later!";
+	fi
 	echo "Configuration script failed!"
 	exit 1;;
-  ?*)	echo "You have Objective-Caml $CAMLVERSION. Good!";;
-  *) echo "I found the Objective-Caml compiler but cannot find its version number!"
-     echo "Is it installed properly ?"
-     echo "Configuration script failed!"
-     exit 1;;
+  3.08*)
+	echo "You have Objective-Caml $CAMLVERSION. Good!";;
+  ?*)
+	CAMLP4COMPAT="-loc loc" 
+	echo "You have Objective-Caml $CAMLVERSION. Good!";;
+  *)
+	echo "I found the Objective-Caml compiler but cannot find its version number!"
+	echo "Is it installed properly ?"
+	echo "Configuration script failed!"
+	exit 1;;
 esac
 
 CAMLTAG=OCAML`echo $CAMLVERSION | sed -e "s/\([1-9]\)\.\([0-9]*\).*/\1\2/g"`
@@ -502,6 +511,7 @@ sed -e "s|LOCALINSTALLATION|$local|" \
     -e "s|CAMLP4BINDIRECTORY|$CAMLP4BIN|" \
     -e "s|CAMLP4LIBDIRECTORY|$CAMLP4LIB|" \
     -e "s|CAMLP4TOOL|$camlp4o|" \
+    -e "s|CAMLP4COMPATFLAGS|$CAMLP4COMPAT|" \
     -e "s|COQDEBUGFLAG|$coq_debug_flag|" \
     -e "s|COQPROFILEFLAG|$coq_profile_flag|" \
     -e "s|BESTCOMPILER|$best_compiler|" \
