Changement de la version minimale requise de OCaml (3.07 => 3.09.3).
J'ai ajouté une option '-force-caml-version' au ./configure pour
passer outre la vérification de la version de OCaml. La barre a été
mise à 3.09.3 parce que Khepri (Debian Etch = oldstable) continue de
faire tourner le bench en utilisant OCaml 3.09.3.

Pour info, Coq 8.2 compile avec la 3.08.4, mais pas le trunk.

git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/trunk@12473 85f007b7-540e-0410-9357-904b9bb8a0f7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -140,6 +140,8 @@ wwwcoq_spec=no
 with_geoproof=false
 with_doc=all
 with_doc_spec=no
+force_caml_version=no
+force_caml_version_spec=no
 
 COQSRC=`pwd`
 
@@ -256,6 +258,9 @@ while : ; do
     -debug|--debug) coq_debug_flag=-g;;
     -profile|--profile) coq_profile_flag=-p;;
     -annotate|--annotate) coq_annotate_flag=-dtypes;;
+    -force-caml-version|--force-caml-version|-force-ocaml-version|--force-ocaml-version) 
+          force_caml_version_spec=yes
+	  force_caml_version=yes;;
     *) echo "Unknown option \"$1\"." 1>&2; usage; exit 2;;
   esac
   shift
@@ -421,17 +426,15 @@ esac
 CAMLVERSION=`"$bytecamlc" -version`
 
 case $CAMLVERSION in
-    1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05|3.06|3.08.0)
+    1.*|2.*|3.00|3.01|3.02|3.03|3.03alpha|3.04|3.05beta|3.05|3.06|3.07*|3.08*|3.09.[012])
 	echo "Your version of Objective-Caml is $CAMLVERSION."
-	if [ "$CAMLVERSION" = "3.08.0" ] ; then
-	    echo "You need Objective-Caml 3.07 or later (to the exception of 3.08.0)!"
+	if [ "$force_caml_version" = "yes" ]; then
+	    echo "WARNING: you are compiling Coq with an outdated version of Objective-Caml"
 	else
-	    echo "You need Objective-Caml 3.07 or later!"
-	fi
-	echo "Configuration script failed!"
-	exit 1;;
-    3.07*|3.08*)
-	echo "You have Objective-Caml $CAMLVERSION. Good!";;
+	    echo "You need Objective-Caml 3.09.3 or later"
+	    echo "Configuration script failed!"
+	    exit 1
+	fi;;
     ?*)
 	CAMLP4COMPAT="-loc loc" 
 	echo "You have Objective-Caml $CAMLVERSION. Good!";;
@@ -453,7 +456,7 @@ case $ARCH in
       CAMLLIB=`"$CAMLC" -where`
 esac
 
-# We need to set va special flag for OCaml 3.07
+# We need to set a special flag for OCaml 3.07
 case  $CAMLVERSION in 
 	3.07*)
 	  cflags="$cflags -DOCAML_307";;
