Détection de camlp5 5.00 au configure
git-svn-id: svn+ssh://scm.gforge.inria.fr/svn/coq/trunk@10190 85f007b7-540e-0410-9357-904b9bb8a0f7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -411,6 +411,13 @@ else
     CAMLP4LIB=+$CAMLP4
 fi
 
+if [ "$CAMLP4" = "camlp5" ] && `$camlp4oexec -v 2>&1 | grep -q 5.00`; then
+    echo "Camlp5 version 5.00 not supported: versions 4.0x or >= 5.01 are OK."
+    echo "Configuration script failed!"
+    exit 1
+fi
+
+
 case $CAMLP4LIB in
     +*) FULLCAMLP4LIB=$CAMLLIB/`echo $CAMLP4LIB | cut -b 2-`;;
     *)  FULLCAMLP4LIB=$CAMLP4LIB;;
